version: "3.7"

# NETWORKS
networks:
  estate-network:
    driver: overlay
    name: estate-network

# VOLUMES
volumes:
  data:
    driver: local
    name: data
    driver_opts:
      type: cifs
      device: //192.168.142.196/data/
      o: "username=kynhanht,password=kynhan123ht,file_mode=0777,dir_mode=0777,vers=1.0"
      # Test mount volume: mount -t cifs -o user=kynhanht,password=kynhan123ht //192.168.142.196/data  /data
      # Test samba: smbclient //192.168.142.196/data -U kynhanht
services:
  # SAMBA
  samba:
    image: kynhanht/samba #dperson/samba
    ports:
      - 139:139
      - 145:145
    environment:
      smbuser: kynhanht
      password: kynhan123ht
    volumes:
      - /home/estate/nginx/conf:/data
    networks:
      - estate-network
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.role==manager
  # MYSQL
  mysql-db:
    image: mysql:8.0.13
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    ports:
      - 3306:3306
    volumes:
      - /home/estate/db:/var/lib/mysql
    networks:
      - estate-network
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: Nhan@123456
      MYSQL_USER: kynhanht
      MYSQL_PASSWORD: Nhan@123456
      MYSQL_DATABASE: estate
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  # NGINX SERVER
  nginx-server:
    image: nginx:1.23.1
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    volumes:
      - data:/etc/nginx/conf.d
    networks:
      - estate-network






